// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdminSideList: typeof import('./components/AdminSideList.vue')['default']
    AdminSideNav: typeof import('./components/AdminSideNav.vue')['default']
    AdminTopNav: typeof import('./components/AdminTopNav.vue')['default']
    AirdnaRentalizer: typeof import('./components/AirdnaRentalizer.vue')['default']
    FormOwner: typeof import('./components/FormOwner.vue')['default']
    FormProperty: typeof import('./components/FormProperty.vue')['default']
    Forms: typeof import('./components/Forms.vue')['default']
    PeopleSideList: typeof import('./components/PeopleSideList.vue')['default']
    PropertyMainTabs: typeof import('./components/PropertyMainTabs.vue')['default']
    PropertySideDetails: typeof import('./components/PropertySideDetails.vue')['default']
    PropertySideList: typeof import('./components/PropertySideList.vue')['default']
    PropertyTopDetails: typeof import('./components/PropertyTopDetails.vue')['default']
    SiteCalendar: typeof import('./components/SiteCalendar.vue')['default']
    SiteDeleteButton: typeof import('./components/SiteDeleteButton.vue')['default']
    SiteDialog: typeof import('./components/SiteDialog.vue')['default']
    SiteEditButton: typeof import('./components/SiteEditButton.vue')['default']
    SiteForm: typeof import('./components/SiteForm.vue')['default']
    SiteQuickAdd: typeof import('./components/SiteQuickAdd.vue')['default']
  }
}

export { }
