// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdminSideList: typeof import('./components/AdminSideList.vue')['default']
    AdminSideNav: typeof import('./components/AdminSideNav.vue')['default']
    AdminTopNav: typeof import('./components/AdminTopNav.vue')['default']
    AirdnaRentalizer: typeof import('./components/AirdnaRentalizer.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FormOwner: typeof import('./components/FormOwner.vue')['default']
    FormProperty: typeof import('./components/FormProperty.vue')['default']
    Forms: typeof import('./components/Forms.vue')['default']
    PeopleSideList: typeof import('./components/PeopleSideList.vue')['default']
    PropertyMainTabs: typeof import('./components/PropertyMainTabs.vue')['default']
    PropertySideDetails: typeof import('./components/PropertySideDetails.vue')['default']
    PropertySideList: typeof import('./components/PropertySideList.vue')['default']
    PropertyTopDetails: typeof import('./components/PropertyTopDetails.vue')['default']
    SiteCalendar: typeof import('./components/SiteCalendar.vue')['default']
    SiteDeleteButton: typeof import('./components/SiteDeleteButton.vue')['default']
    SiteDialog: typeof import('./components/SiteDialog.vue')['default']
    SiteEditButton: typeof import('./components/SiteEditButton.vue')['default']
    SiteForm: typeof import('./components/SiteForm.vue')['default']
    SiteQuickAdd: typeof import('./components/SiteQuickAdd.vue')['default']
  }
}

export { }
