// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdminSideList: typeof import('./components/AdminSideList.vue')['default']
    AdminSideNav: typeof import('./components/AdminSideNav.vue')['default']
    AdminTopNav: typeof import('./components/AdminTopNav.vue')['default']
    FormOwner: typeof import('./components/FormOwner.vue')['default']
    FormProperty: typeof import('./components/FormProperty.vue')['default']
    PeopleSideList: typeof import('./components/PeopleSideList.vue')['default']
    PropertySideList: typeof import('./components/PropertySideList.vue')['default']
    SiteDialog: typeof import('./components/SiteDialog.vue')['default']
  }
}

export { }
